import Lottie from '../components/lottie/lottie'
import Head from 'next/head'
import Intro from '../components/intro'
import styled from 'styled-components'
import Skill from '../components/skill'
import Header from '../components/header/header'

const AboutContainer = styled.div`
  padding: 1rem;
  display: flex;
  flex-direction: column;
  height: 100vh;
  gap: 2rem;
`
const AboutLayout = styled.div`
  width: 100%;
  display: flex;
`

const AboutLayoutLeft = styled.div`
  width: 58%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  justify-content: space-between;
`
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <AboutContainer>
          <Header item={['긍정적인','배움을 즐기는', '열정있는']}/>
          <AboutLayout>
            <AboutLayoutLeft>
              <Intro/>
              <Skill className='reveal-skill'/>
            </AboutLayoutLeft>
            <Lottie className='reveal-lottie'/>
          </AboutLayout>
        </AboutContainer>
      </main>


    </div>
  )
}
